version: '3.6'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.11.119
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    container_name: logstash
    networks: ['stack']
    depends_on: ['kafka']
    volumes:
      - /home/elk/docker-kafka/config/logstash.yml:/usr/share/logstash/logstash.yml
      - /home/elk/docker-kafka/config/logstash.conf:/usr/share/logstash/logstash.conf
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    ports: ['9200:9200']
    networks: ['stack']
    depends_on: ['logstash']
    volumes:
      - /home/elk/docker-kafka/config/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana
    ports: ['5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']
    volumes:
      - /home/elk/docker-kafka/config/kibana.yml:/usr/share/kibana/kibana.yml

networks: {stack: {}}
