
# read password from logstash.keystore
# xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
#xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch.url: https://localhost:9200

# xpack.monitoring.elasticsearch.username: logstash_system
